name: NENORY MUSIC APP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev


jobs:
  node-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          check-latest: true
      - name: Install NPM dependencies
        run: npm install
      - name: Compile assets for production
        run: npm test
